apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-gf-ocp-sealed-secrets
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/RobMokkink/openshift-argocd-setup-and-examples.git
      revision: HEAD
      files:
      - path: <PATH>
  template:
    metadata:
      name: ocp-{{cluster.name}}-sealed-secrets
    spec:
      project: default
      source:
        repoURL: https://github.com/RobMokkink/openshift-argocd-setup-and-examples.git
        targetRevision: HEAD
        path: components/infra-apps/sealed-secrets/overlays/openshift
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
