apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators
bases:
- ../../base
resources:
  - cluster-admin-rolebinding.yaml

patchesJSON6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-gitops-operator
      namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
